### ISSUE TITLE
Dataset/model availability

### ISSUE THREAD

**Issue by anoopkunchukuttan** [ltrc/Mukhyansh#1]
Hi, 
Can you indicate when will the dataset and model be released?

**Comment by lokeshmadasu42** [comment]
Hi,

We have updated the repository. You can download the dataset from following link : https://drive.google.com/drive/folders/1PYUgWMqELhVbQ_nJ7EtpYo_R1xm7XM6y

And, soon we will share our huggingface model checkpoints.
